[package]
name = "metaserve-proto"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
edition = "2021"

[dependencies]
serde = { version = "1.0.80", features = ["derive"] }

